{{- if .Values.scheduling.userScheduler.enabled -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "jupyterhub.user-scheduler-deploy.fullname" . }}
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
data:
  config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1beta3
    kind: KubeSchedulerConfiguration
    leaderElection:
      resourceLock: endpoints
      resourceName: {{ include "jupyterhub.user-scheduler-lock.fullname" . }}
      resourceNamespace: "{{ .Release.Namespace }}"
    profiles:
      - schedulerName: {{ include "jupyterhub.user-scheduler.fullname" . }}
        {{- with .Values.scheduling.userScheduler.plugins }}
        plugins:
          {{- . | toYaml | nindent 10 }}
        {{- end }}
        {{- with .Values.scheduling.userScheduler.pluginConfig }}
        pluginConfig:
          {{- . | toYaml | nindent 10 }}
        {{- end }}
    {{- end }}
{{- end }}
